### ISSUE TITLE
"TransferAndCall" I always failed to call 

### ISSUE THREAD

**Issue by RNHaoHao** [windingtree/erc827#10]
"TransferAndCall" I always failed to call （"0xacb6208f4fbc6ac8fb60ad92f7096b4100538f45",100,"0xa9059cbb0000000000000000000000004ffe370c88549717a552f9ed7aac84b12e6bc1680000000000000000000000000000000000000000000000000de0b6b3a7640000"）

**Comment by RNHaoHao** [comment]
![image](https://user-images.githubusercontent.com/33622382/48107766-ccd27700-e27b-11e8-8437-93ad1ef8e7f0.png)
"TransferAndCall" I always failed to call

**Comment by AugustoL** [comment]
Please provide a more detailed explanation of the issue in the gitter channel https://gitter.im/ERC827
