### ISSUE TITLE
ERC827 or ERC20

### ISSUE THREAD

**Issue by RNHaoHao** [windingtree/erc827#6]
I issue a erc827 token contract. How do I still display the erc20 token on the browser?

**Comment by AugustoL** [comment]
@RNHaoHao what do you mean on the browser? It works exactly the same like ERC20

**Comment by RNHaoHao** [comment]
@AugustoL  Send a token of ERC827. Is it still a ERC20 token? Do you have a complete 827 contract source code? Are there many loopholes now?

**Comment by AugustoL** [comment]
@RNHaoHao You have the contract implementation in the contracts folder. Is not safe to use yet.
